[project]
name = "notion-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "notion-client>=2.7.0",
    "pydantic>=2.9.0",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
